# Grafana InfluxDB Datasource Configuration
# REQ: REQ-P0-1768148786448-3r439 - Database stress testing

apiVersion: 1

datasources:
  - name: InfluxDB_K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: agogsaas
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: k6-admin-token
    isDefault: true
    editable: true
